accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView

# from django.contrib.auth.views import LogoutView
from django.urls import path
from accounts.views import signup

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

projects/urls.py
from projects.views import (
    ProjectDetailView,
    ProjectListView,
    ProjectCreateView,
)

from django.urls import path


urlpatterns = [
    path("", ProjectListView.as_view(), name="list_projects"),
    path("<int:pk>/", ProjectDetailView.as_view(), name="show_project"),
    path("create/", ProjectCreateView.as_view(), name="create_project"),
]

tasks/urls.py
from tasks.views import TaskCreateView, TaskListView, TaskUpdateView

from django.urls import path

urlpatterns = [
    path("create/", TaskCreateView.as_view(), name="create_task"),
    path("mine/", TaskListView.as_view(), name="show_my_tasks"),
    path("<int:pk>/complete/", TaskUpdateView.as_view(), name="complete_task"),
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("projects/", include("projects.urls")),
    path("accounts/", include("accounts.urls")),
    path("tasks/", include("tasks.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("list_projects")),
        name="home",
    ),
]

accounts/models.py
# Create your models here.

projects/models.py
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL

# Create your models here.


class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    members = models.ManyToManyField(USER_MODEL, related_name="projects")

    def __str__(self):
        return self.name

tasks/models.py
from django.db import models

from projects.models import USER_MODEL, Project

# Create your models here.


class Task(models.Model):
    name = models.CharField(max_length=200)
    start_date = models.DateTimeField()
    due_date = models.DateTimeField()
    is_completed = models.BooleanField(default=False)
    project = models.ForeignKey(
        Project, related_name="tasks", on_delete=models.CASCADE
    )
    assignee = models.ForeignKey(
        USER_MODEL, null=True, related_name="tasks", on_delete=models.SET_NULL
    )

    def __str__(self):
        return self.name

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

# Create your views here.


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password1")
            user = User.objects.create_user(
                username=username,
                password=password,
            )
            user.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm(request.POST)

    context = {
        "form": form,
    }
    return render(request, "registration/signup.html", context)

projects/views.py
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
from projects.models import Project

# Create your views here.


class ProjectListView(LoginRequiredMixin, ListView):
    model = Project
    template_name = "project/list.html"

    def get_queryset(self):
        return self.model.objects.filter(members=self.request.user)


class ProjectDetailView(LoginRequiredMixin, DetailView):
    model = Project
    template_name = "project/detail.html"


class ProjectCreateView(LoginRequiredMixin, CreateView):
    model = Project
    template_name = "project/create.html"
    fields = ["name", "description", "members"]

    def get_success_url(self):
        return reverse_lazy("show_project", args=[self.object.id])

tasks/views.py
from django.shortcuts import redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView

from tasks.models import Task

# Create your views here.


class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    template_name = "task/create.html"
    fields = ["name", "start_date", "due_date", "project", "assignee"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.member = self.request.user
        item.save()
        return redirect("show_project/int:pk")


class TaskListView(LoginRequiredMixin, ListView):
    model = Task
    template_name = "task/list.html"

    def get_queryset(self):
        return self.model.objects.filter(assignee=self.request.user)


class TaskUpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    fields = ["is_completed"]
    success_url = reverse_lazy("show_my_tasks")

projects/templates/base.html
{%load static%}
<!doctype html>
<html lang='en'>
    <head>
        <title>HR Mod1 Assessment</title>
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    {%if user.is_authenticated%}
                        <li><a href="{%url 'show_my_tasks'%}">My tasks</a></li>
                        <li><a href="{%url 'list_projects'%}">My projects</a></li>
                        <li><a href="{% url 'logout'%}">Logout</a></li>
                    {%else%}
                        <li><a href="{%url 'login'%}">Login</a></li>
                        <li><a href="{%url 'signup'%}">Sign Up</a></li> 
                    {%endif%}
                </ul>
            </nav>
        </header>
        {%block content%}
        {%endblock content%}
    </body>
</html>

projects/templates/project/create.html
{%extends 'base.html'%}

{%block content%}
    <main>
        <div>
            <h1>Create a new project</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type='submit'>Create</button>
            </form>
        </div>
    </main>


{%endblock content%}

projects/templates/project/detail.html
{%extends 'base.html'%}
{% load markdownify %}

{%block content%}
    <main>
        <div>
            <h1>{{project.name}}</h1>
            <p>{{ project.description|markdownify }}</p>
            <h2>Tasks</h2>
            <a href="{%url 'create_task'%}">Create a new task</a>
            {%if project.tasks.all %}
                <table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Assignee</th>
                            <th>Start date</th>
                            <th>Due date</th>
                            <th>Is completed</th>
                        </tr>
                    </thead>
                    <tbody>
                        {%for x in project.tasks.all%}
                            <tr>
                                <td>{{x.name}}</td>
                                <td>{{x.assignee}}</td>
                                <td>{{x.start_date}}</td>
                                <td>{{x.due_date}}</td>
                                {%if x.is_completed == True%}
                                    <td>yes</td>
                                {%else%}
                                    <td>no</td>
                                {%endif%}
                            </tr>
                        {%endfor%}
                    </tbody>
                </table>
            {%else%}
                <p>This project has no tasks</p>
            {%endif%}
        </div>
    </main>

{%endblock content%}

projects/templates/project/list.html
{%extends 'base.html'%}
{%block content%}
    <main>
        <div>
            <h1>My Projects</h1>
            {%if project_list == False %}
                <p>You are not assigned any projects</p>
            {%else %}
                <table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Number of tasks</th>
                        </tr>
                    </thead>
                    <tbody>
                        {%for i in project_list%}
                            <tr>
                                <td><a href="{%url 'show_project' i.pk%}">{{i.name}}</a></td>
                                <td>{{i.tasks.all|length}}</td>
                            </tr>
                        {%endfor%}
                    </tbody>
                </table>
            {%endif%}
            <a href="{%url 'create_project'%}"><button>Create new project</button></a>
        </div>
    </main>
{%endblock content%}

tasks/templates/task/create.html
{%extends 'base.html'%}

{%block content%}
    <main>
        <div>
            <h1>Create a new task</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type='submit'>Create</button>
            </form>
        </div>
    </main>
{%endblock content%}

tasks/templates/task/list.html
{%extends 'base.html'%}

{%block content%}
    <main>
        <div>
            <h1>My Tasks</h1>
            {%if task_list %}
                <table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Start date</th>
                            <th>End date</th>
                            <th>Is completed</th>
                        </tr>
                    </thead>
                    <tbody>
                        {%for i in task_list%}
                            <tr>
                                <td>{{i.name}}</td>
                                <td>{{i.start_date}}</td>
                                <td>{{i.end_date}}</td>
                                <td>
                                    {%if i.is_completed == False%}
                                        <form method="post" action="{% url 'complete_task' i.pk %}">
                                            {% csrf_token %}
                                            <input type="hidden" name="is_completed" value="True">
                                            <button>Complete</button>
                                        </form>
                                    {%else%}
                                        Done
                                    {%endif%}
                                </td>
                            </tr>
                        {%endfor%}
                    </tbody>
                </table>
            {%else%}
                <p>You have no tasks<p>
            {%endif%}
        </div>
    </main>
{%endblock content%}